### ISSUE TITLE
Game pieces partially rendered while computer "thinks"

### ISSUE THREAD

**Issue by barrybecker4** [bb4/bb4-games#31]
While the computer calculates its next move, the rendering (which is in a separate thread) often draws a game board reflecting what the computer is thinking about. I used to think this was sort of a feature, but it can be distracting and confusing.

**Comment by barrybecker4** [comment]
I can even get a concurrent modification to occur if resize the board while the computer is thinking.
stale abs health. recalculating relative health
Exception in thread "Worker Thread" java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
	at java.util.AbstractCollection.addAll(Unknown Source)
	at com.barrybecker4.game.twoplayer.go.board.elements.group.GoGroup.getLiberties(GoGroup.java:200)
	at com.barrybecker4.game.twoplayer.go.board.elements.group.GoGroup.getNumLiberties(GoGroup.java:213)
	at com.barrybecker4.game.twoplayer.go.board.analysis.group.AbsoluteHealthCalculator.calculateAbsoluteHealth(AbsoluteHealthCalculator.java:98)
	at com.barrybecker4.game.twoplayer.go.board.analysis.group.GroupAnalyzer.calculateAbsoluteHealth(GroupAnalyzer.java:128)
	at com.barrybecker4.game.twoplayer.go.board.analysis.territory.TerritoryUpdater.calcAbsoluteHealth(TerritoryUpdater.java:109)
	at com.barrybecker4.game.twoplayer.go.board.analysis.territory.TerritoryUpdater.updateTerritory(TerritoryUpdater.java:63)
	at com.barrybecker4.game.twoplayer.go.board.analysis.WorthCalculator.calculateWorth(WorthCalculator.java:97)
	at com.barrybecker4.game.twoplayer.go.board.analysis.WorthCalculator.worth(WorthCalculator.java:50)
	at com.barrybecker4.game.twoplayer.go.board.analysis.BoardEvaluator.worth(BoardEvaluator.java:49)
	at com.barrybecker4.game.twoplayer.go.board.GoSearchable.worth(GoSearchable.java:143)
	at com.barrybecker4.game.twoplayer.go.board.move.GoMoveGenerator.setMoveValue(GoMoveGenerator.java:99)
	at com.barrybecker4.game.twoplayer.go.board.move.GoMoveGenerator.generateEvaluatedMoves(GoMoveGenerator.java:46)
	at com.barrybecker4.game.twoplayer.go.board.GoSearchable.generateMoves(GoSearchable.java:304)
	at com.barrybecker4.game.twoplayer.go.board.GoSearchable.generateMoves(GoSearchable.java:22)
	at com.barrybecker4.game.twoplayer.common.search.strategy.AbstractBruteSearchStrategy.searchInternal(AbstractBruteSearchStrategy.java:90)
	at com.barrybecker4.game.twoplayer.common.search.strategy.NegaScoutStrategy.findBestMove(NegaScoutStrategy.java:102)
	at com.barrybecker4.game.twoplayer.common.search.strategy.AbstractBruteSearchStrategy.searchInternal(AbstractBruteSearchStrategy.java:101)
	at com.barrybecker4.game.twoplayer.common.search.strategy.NegaScoutStrategy.findBestMove(NegaScoutStrategy.java:102)
	at com.barrybecker4.game.twoplayer.common.search.strategy.AbstractBruteSearchStrategy.searchInternal(AbstractBruteSearchStrategy.java:101)
	at com.barrybecker4.game.twoplayer.common.search.strategy.NegaScoutStrategy.findBestMove(NegaScoutStrategy.java:102)
	at com.barrybecker4.game.twoplayer.common.search.strategy.AbstractBruteSearchStrategy.searchInternal(AbstractBruteSearchStrategy.java:101)
	at com.barrybecker4.game.twoplayer.common.search.strategy.NegaMaxStrategy.search(NegaMaxStrategy.java:32)
	at com.barrybecker4.game.twoplayer.common.AbstractSearchable.searchForNextMove(AbstractSearchable.java:47)
	at com.barrybecker4.game.twoplayer.common.TwoPlayerController.findComputerMove(TwoPlayerController.java:265)
	at com.barrybecker4.game.twoplayer.common.TwoPlayerSearchWorker$1.construct(TwoPlayerSearchWorker.java:67)
	at com.barrybecker4.common.concurrency.Worker$1.run(Worker.java:39)
	at java.lang.Thread.run(Unknown Source)
